### PR TITLE
This PR renames directories to make things easier to find for nexft year

### PR DESCRIPTION
**Pull request by lwasser**
note: we may need to revisit some of the notebooks and clean up fixed versions and such of things. 
this PR has a conflict so we can wait to clean it up and such until later as well. this will prevent us from merging it too soon!

### CODE REVIEW

**Comment by nkorinek** [comment]
@lwasser Hey, I was looking at making a PR for this repo, and noticed this hasn't been merged yet. My local copy has all the updated file names, but the master branch here doesn't. Can we merge this soon? I can fix the conflicts. Thanks!

**Comment by lwasser** [comment]
@nkorinek i think we just need to fix that merge conflict. do you think you can do it and we can then merge?  i hadn't merged so students don't have 2 copies of notebooks in the hub but at this point i think it could be ok. Alternatively you could make a new PR with all of the name changes and such. whatever works and then we can merge!!

**Comment by nkorinek** [comment]
Fixed the error, seems like it was a few left over files from a folder that should have been deleted b/c it was renamed.

**Comment by nkorinek** [comment]
Pushed up another commit b/c I noticed a few other redundant or misnamed folders that could be fixed here. Took care of the merge conflicts! @lwasser

**Comment by lwasser** [comment]
so is this ready to merge? i'm on my way out but can merge it now without checking it! have you double checked it? thank you !!!

**Comment by lwasser** [comment]
i can merge tonight when i'm back if you leae a message!!

**Comment by nkorinek** [comment]
@lwasser alright I reviewed the files again and I removed even more redundant folders. I also removed the "fixed" versions of the files in the data-types week since we updated the main files to be identical to the fixed versions.

**Comment by lwasser** [comment]
awesome. thank you @nkorinek  i'll go ahead and merge this!!

**Pull request merged**
