### PR TITLE
Updates to Week 1 Python Fundamentals Notebooks

### PR DESCRIPTION
**Pull request by jlpalomino**
@lwasser This PR makes small updates throughout the week 1 Python Fundamentals notebooks, which are based on testing feedback from Nate Q.

### CODE REVIEW

**Comment by lwasser** [comment]
hey @jlpalomino - thank you for these edits. so one note - these lessons will ultimately go in our textbook. it's not normal for text to have a new line for each sentence in a textbook or when you are reading. i think that is not ideal for readability. i've actually been creating paragraphs in most of the lessons and then for the notebooks i have been trying to keep the text to 79 characters using a ruler for readability. it looks like some of that was undone in this pr. did you have a reason for doing that? most paragraphs are composed of multiple sentences. 

this is a good example of a page where there are a ton of line breaks:

https://www.earthdatascience.org/courses/intro-to-earth-data-science/python-code-fundamentals/get-started-using-python/

https://www.earthdatascience.org/courses/intro-to-earth-data-science/python-code-fundamentals/get-started-using-python/variables/

it just becomes really difficult to read because it breaks up visual hierarchy. and it's not ideal style for a book reading. Let's just come to a consensus on it because i don't want to edit this and then have it undone !

**Comment by lwasser** [comment]
ways to break up text include bulleted lists, headings and subheadings, code in between paragraphs, images and then we can use styles to adjust line spacing and such. but manual returns for each sentence i think is not ideal.

**Comment by nkorinek** [comment]
@lwasser @jlpalomino changes are in!

**Comment by lwasser** [comment]
thank you @nkorinek !!

**Comment by lwasser** [comment]
it will be good to do a build of these lessons to see how they look in our book next week!! even just one lesson

**Pull request merged**
