### PR TITLE
Python fundamentals exercises

### PR DESCRIPTION
**Pull request by nkorinek**
Modified the lessons from [earthlab](https://www.earthdatascience.org/courses/intro-to-earth-data-science/python-code-fundamentals/) to have more activies. The variables lesson is in #3 so that it's easier to review by itself.

### CODE REVIEW

**Comment by nkorinek** [comment]
@jlpalomino hey! I pushed some changes up to here. I would appreciate a review when you get a second. I think there's still more work to be done, but I would like your advice. specifically, I would like advice on the last activity in the operators notebook, I'm sure there's a better way to do that but I just don't know how. Thanks!

**Comment by nkorinek** [comment]
I've been looking at the exercise section, which was copy/pasted from the end of one of the lessons. Do we want to import matplotcheck so that we can check the plot produced here, or should we come up with a new exercise? Thoughts @jlpalomino @lwasser ?

**Comment by jlpalomino** [comment]
Great job on these notebooks @nkorinek!  I've made some minor changes to the lists notebook, and I am wrapping up minor changes to the operators notebook (I'll push those up shortly).

I like the idea of adding in some tests into the exercise notebook! They can be simple ones that check for the following:

- the lists contain the correct values: 
`months = ["Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"]`
`precip = [jan, feb, mar, apr, may, june, july, aug, sept, oct, nov, dec] `
- plot is a bar plot (and specify this in the instructions)
- the title contains: Boulder, average or mean, month, precip
- y axis label contains: precip, mm or millimeters
- x axis label contains: month

So please add those tests to the notebook and also remove the existing code from the notebook (I will refrain from making any changes to that exercise notebook for now).

**Comment by nkorinek** [comment]
Thanks for the feedback and edits @jlpalomino !!

**Comment by jlpalomino** [comment]
Sure thing @nkorinek!  

About the last exercise in the operators notebook, I like it! I made a few modifications that you can pull, including adding a set of `()` around the condition, so that it is easier to read.

I think what is needed before that exercise are examples throughout the notebook that show how you can create variables that contain a condition, so that the users are not confused by the syntax that is being used in the exercise. So I would add a few examples of that in the last few operator sections.

**Comment by nkorinek** [comment]
@jlpalomino seeing those changes, looks great! Also the changes in the list notebook were great, those variables make the exercises much more relevant/understandable, thanks! 

I can definitely add those examples in before that last activity. I'll make that change and the ones to the exercise notebook and push it up asap, probably early monday, and make sure to ping you for another review, thanks for all the help with this!

**Comment by jlpalomino** [comment]
Monday sounds good @nkorinek!  Thanks again for your great work on these notebooks.

**Comment by jlpalomino** [comment]
I forgot to mention one minor thing in the operators notebook @nkorinek Can you modify the test in cell14 to check that the object `annual_avg_precip_nyc` has been created (like you do with try/except in the other tests)? Otherwise, if a student tries to run all cells in the notebook at the beginning, the test in cell 14 will fail rather than telling them that the object does not exist. Thanks!

**Comment by nkorinek** [comment]
@jlpalomino @lwasser I've added in the changes that @jlpalomino requested, should be ready for a review now!

**Comment by jlpalomino** [comment]
Thanks @nkorinek!  The operators notebook looks really good!  I made a few small edits to the exercise notebook to clarify the language a bit and modified the tests to match the keywords to the appropriate axis label.

@lwasser This PR is ready for your review. 

Minor thing about jupytext - the changes that I made to the exercise notebook did not prompt a change in the md file this time.  Not sure why, but in case you open the md, you will see that it did not have changes committed.

**Comment by lwasser** [comment]
ok great. guys ... i'm just curious why we are using md files vs py files? i think py will be better. any objections to switching @jlpalomino @nkorinek ?? i'll for the meantime work on the notebooks! THANK YOU.

**Comment by jlpalomino** [comment]
No objections on my end. I have actually only been modified the notebooks but I was committing the md files that were tracked as changed by git.

**Comment by lwasser** [comment]
ok @nkorinek i've only edited teh variables lessons. let's do the following.

1. for these notebooks let's just add a top bar that says earth lab (like we have for our homework assignments) on each notebook. 
2. let's go ahead and add data tips like we have in our lessons. i know it won't render perfectly but we can fix that in the future. for now let's add them as html like we do in the lessons. i've created TODO's for this.
3. finally when there are discussions that we have lessons for, let's link to those in the text. i've added some TODO's for that as well.

Where ever you see a change to add interactive cells that people can run to break up text, let's do that. i've added some in here already!! 

as you finish up the notebook you can delete my TODO text. i'll work on the other 3 lessons later tonight after my doc appt!! thank you.

**Comment by lwasser** [comment]
oh - let's also use the same naming convention that we use for our other lessons so please add 01, 02 etc to ensure the notebooks are in the correct order !

**Comment by jlpalomino** [comment]
Good idea to have the print cells be explicitly identified as interactive cells @lwasser!  I was initially thinking that we could post the notebooks without any of the cells run in advance, so they would need to run each cell.  Your suggestion gets them coding asap.

@nkorinek If you have any trouble finding related lessons in our textbooks, let me know!

**Comment by lwasser** [comment]
this is looking great. @nkorinek  a few minor things. i noticed Python is sometimes bolded and other times not. let's be consistent and use bold for each time we use the word python! 
i've updated the first few lessons with data tips and breakout boxes for challenges. i've also updated some of the challenges. 

i'd like to 

1. review the memory allocation item that you and i discussed today associated with the `is`operator. -- tomorrow is just fine no rush. 
2. review that operator lesson again. there is a LOT there now. 
3. i need to still look at the final exercise. just ran out of time today. i may look at it later or i may just take a break and do it tomorrow.

either way it's all looking great and i can't wait to add this all back to the textbook as well. yay better lessons. 

notes
* i think we should have a data types lessons in the intro textbook that covers floats, and strings and all the different data types in python -- FUTURE TODO :) 
* I think teh challenges can be more challenging adding new items to show them how to do something related and then asking them to implement that. example: see how i had them index a list of lists in the list lesson! i showed them something new and had them do something with it! the carpentries doe that a lot and i think it works well!! 

nice work on this!!

**Comment by jlpalomino** [comment]
@lwasser @nkorinek Great revisions to the exercise notebook. A few suggestions:

1. Add the unit conversion from inches to mm (`1 inch = 25.4 mm`) , so that students know what to use. @lwasser suggested adding a prompt for the students to create a variable with this value, so that they can use it for calculation.

2. The paragraph for the List Comprehension section is a bit long, so breaking it up with make it easier to read. I suggest a new paragraph starting at: "The syntax for a list...".  

3. Either provide the result for `my_new_list` in the Markdown, or prompt the students to run the code to see the results are the original values multiplied by 2. 

4. We don't have a lesson on list comprehension, but I wonder if we should add a link to one (or a link to our intro to loops chapter?) to support the explanation of `i`.

**Comment by nkorinek** [comment]
@jlpalomino on it!

**Comment by jlpalomino** [comment]
Thanks @nkorinek! (I would do myself but busy preparing for class!)

**Comment by nkorinek** [comment]
Alright @jlpalomino I added in the changes you've requested to the notebook, hopefully they were what you were looking for!

**Comment by lwasser** [comment]
ok team - great work pulling this together!! merging it now!

**Pull request merged**
